apiVersion: v2
name: openmetadata-dependencies
description: Helm Dependencies for OpenMetadata

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.11.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.11.2"

home: https://open-metadata.org/

sources:
  - https://github.com/open-metadata/OpenMetadata
  - https://github.com/open-metadata/openmetadata-helm-charts

keywords:
  - metadata
  - data-science
  - data
  - machine-learning
  - automation
  - big-data
  - bigdata
  - artificial-intelligence
  - datascience
  - data-engineering
  - data-catalog
  - metadata-api
  - governance
  - data-profiling
  - metadata-management
  - dataengineering
  - dataquality
  - bigdataanalytics
  - datadiscovery

maintainers:
  - name: OpenMetadata
    email: support@open-metadata.org

icon: https://open-metadata.org/assets/favicon.png

# Add Dependencies of other charts
dependencies:
- name: mysql
  version: "14.0.2"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enabled
- name: airflow
  version: "8.9.0"
  repository: "https://airflow-helm.github.io/charts"
  condition: airflow.enabled
- name: opensearch
  version: "2.35.0"
  repository: "https://opensearch-project.github.io/helm-charts/"
  condition: opensearch.enabled
