{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "OpenMetadata.serviceAccountName" . }}
  labels:
    {{- include "OpenMetadata.labels" . | nindent 4 }} 
  annotations:
  {{- if .Values.annotations }}
    {{- include "OpenMetadata.annotations" . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
