name: Deploy OpenMetadata Stack to AKS

on:
  push:
    branches:
      - main
    paths:
      - "charts/openmetadata/**"
      - ".github/workflows/deploy.yaml"
      - "DockerDockerfile-openmetadata"
      - "Dockerfile-airflow"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CLUSTER_NAME: aks-dev-data-service 
      AZURE_RESOURCE_GROUP: aks-dev-data-service_group
      AZURE_REGION: your-region
      NAMESPACE: daap-dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ env.AZURE_CLUSTER_NAME }}

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: daappoc25.azurecr.io

    - name: Build and push docker
      run:  |
        docker build -t daappoc25.azurecr.io/openmetadata:custom -f Dockerfile-openmetadata .
        docker push daappoc25.azurecr.io/openmetadata:custom
        #docker build -t daappoc25.azurecr.io/airflow:ver-1 -f Dockerfile-airflow .
        #docker push daappoc25.azurecr.io/airflow:ver-1    
      

    - name: Create Namespace /optional
      run: |
        kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE


    - name: Deploy MySQL
      run: |
        kubectl apply -f charts/openmetadata/mysql.yaml -n $NAMESPACE
        kubectl rollout status statefulset/mysql -n $NAMESPACE --timeout=180s

    - name: Deploy OpenSearch
      run: |
        helm repo add opensearch https://opensearch-project.github.io/helm-charts
        helm repo update
        helm upgrade --install opensearch opensearch/opensearch --namespace daap-dev  -f $(pwd)/charts/openmetadata/values-opensearch.yaml
        kubectl apply -f $(pwd)/charts/openmetadata/opensearch-sysctl-daemonset.yaml -n daap-dev

    - name: Generate FERNET & SECRET keys
      run: |
        echo "FERNET_KEY=$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')" >> $GITHUB_ENV
        echo "SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')" >> $GITHUB_ENV

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic airflow-secrets \
          --from-literal=FERNET_KEY=$FERNET_KEY \
          --from-literal=SECRET_KEY=$SECRET_KEY \
          -n daap-dev --dry-run=client -o yaml | kubectl apply -f -
          

    - name: Deploy OpenMetadata (with Airflow)
      run: |
        helm repo add open-metadata https://helm.open-metadata.org 
        helm repo update
        helm upgrade --install openmetadata open-metadata/openmetadata --namespace daap-dev -f $(pwd)/charts/openmetadata/values.yaml

        #kubectl apply -f $(pwd)/charts/openmetadata/airflow.yaml -n daap-dev
        helm repo add apache-airflow https://airflow.apache.org 
        helm repo update
        helm upgrade --install airflow apache-airflow/airflow \
        --version 2.10.5 \
        --namespace daap-dev \
        -f $(pwd)/charts/openmetadata/airflow.yaml \
        --reset-values


